version: '3.8'
services:
  rabbitmq01:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq01
    hostname: rabbitmq01
    ports:
      - "15000:15672"
    volumes:
      - $PWD/.tmp/storage/rabbitmq01:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=topdemais
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=EaeMankkkkk
      - CLUSTERED=true

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 1m
      timeout: 20s
      retries: 3
      start_period: 40s

  rabbitmq02:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq02
    hostname: rabbitmq02
    restart: on-failure
    depends_on:
      - rabbitmq01
    ports:
      - "15001:15672"
    volumes:
      - $PWD/.tmp/storage/rabbitmq02:/var/lib/rabbitmq
      - $PWD/rabbitmq/entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: /usr/local/bin/entrypoint.sh
    environment:
      - RABBITMQ_ERLANG_COOKIE=topdemais
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=EaeMankkkkk
      - CLUSTERED=true

  rabbitmq03:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq03
    hostname: rabbitmq03
    restart: on-failure
    depends_on:
      - rabbitmq01
    ports:
      - "15002:15672"
    volumes:
      - $PWD/.tmp/storage/rabbitmq03:/var/lib/rabbitmq
      - $PWD/rabbitmq/entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: /usr/local/bin/entrypoint.sh
    environment:
      - RABBITMQ_ERLANG_COOKIE=topdemais
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=EaeMankkkkk
      - CLUSTERED=true

  envoy:
    image: envoyproxy/envoy:v1.14-latest
    container_name: envoy
    hostname: envoy
    restart: on-failure
    depends_on:
      - rabbitmq01
      - rabbitmq02
      - rabbitmq03
    ports:
      - "80:15672"
      - "5672:5672"
    volumes:
      - $PWD/envoy/envoy.yaml:/etc/envoy/envoy.yaml


# DEMO APPS

  producer:
    build:
        context: ./producer
        dockerfile: Dockerfile
    environment:
      - AMQP_URL=amqp://admin:EaeMankkkkk@envoy:5672
    ports:
        - 8080:8080
    volumes:
        - ./producer/:/go/src/producer


  consumer:
    build:
        context: ./consumer
        dockerfile: Dockerfile
    environment:
      - AMQP_URL=amqp://admin:EaeMankkkkk@envoy:5672
    ports:
        - 9090:8080
    volumes:
        - ./consumer/:/go/src/consumer
